[2021-08-04 14:32:42,285] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_2 2021-08-04T12:32:39.795977+00:00 [queued]>
[2021-08-04 14:32:42,290] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_2 2021-08-04T12:32:39.795977+00:00 [queued]>
[2021-08-04 14:32:42,290] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:32:42,290] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:32:42,290] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:32:42,296] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_2> on 2021-08-04T12:32:39.795977+00:00
[2021-08-04 14:32:42,298] {standard_task_runner.py:52} INFO - Started process 1347534 to run task
[2021-08-04 14:32:42,301] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task_2', '2021-08-04T12:32:39.795977+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpc0dammys', '--error-file', '/tmp/tmplvec8hl9']
[2021-08-04 14:32:42,302] {standard_task_runner.py:77} INFO - Job 21: Subtask task_2
[2021-08-04 14:32:42,335] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task_2 2021-08-04T12:32:39.795977+00:00 [running]> on host adam
[2021-08-04 14:32:42,356] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T12:32:39.795977+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-04T12:32:39.795977+00:00
[2021-08-04 14:32:42,356] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 14:32:42,357] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2021-08-04 14:32:42,361] {subprocess.py:74} INFO - Output:
[2021-08-04 14:32:42,362] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-04 14:32:42,367] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-04 14:32:42,368] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=trigger_rule, task_id=task_2, execution_date=20210804T123239, start_date=20210804T123242, end_date=20210804T123242
[2021-08-04 14:32:42,392] {local_task_job.py:149} INFO - Task exited with return code 1
