[2021-08-12 15:24:49,856] {taskinstance.py:886} INFO - Dependencies not met for <TaskInstance: parallel_dag_03.processing_tasks.jupyter_task.task_1 2021-08-12T13:10:11.156723+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-08-12 15:24:49,858] {local_task_job.py:96} INFO - Task is not able to be run
