[2021-08-12 10:36:23,361] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [queued]>
[2021-08-12 10:36:23,365] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [queued]>
[2021-08-12 10:36:23,365] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:36:23,365] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 10:36:23,365] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:36:23,373] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_3> on 2021-08-11T00:00:00+00:00
[2021-08-12 10:36:23,374] {standard_task_runner.py:52} INFO - Started process 132374 to run task
[2021-08-12 10:36:23,377] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2021-08-11T00:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/subdag_example.py', '--cfg-path', '/tmp/tmp024f3p2q', '--error-file', '/tmp/tmp0xc8474c']
[2021-08-12 10:36:23,378] {standard_task_runner.py:77} INFO - Job 34: Subtask task_3
[2021-08-12 10:36:23,399] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [running]> on host adam
[2021-08-12 10:36:23,422] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-08-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-11T00:00:00+00:00
[2021-08-12 10:36:23,423] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 10:36:23,423] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'ls']
[2021-08-12 10:36:23,428] {subprocess.py:74} INFO - Output:
[2021-08-12 10:36:23,430] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 10:36:23,443] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20210811T000000, start_date=20210812T083623, end_date=20210812T083623
[2021-08-12 10:36:23,456] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 10:36:23,468] {local_task_job.py:149} INFO - Task exited with return code 0
[2021-08-12 10:37:48,108] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [queued]>
[2021-08-12 10:37:48,112] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [queued]>
[2021-08-12 10:37:48,112] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:37:48,112] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 10:37:48,112] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:37:48,118] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_3> on 2021-08-11T00:00:00+00:00
[2021-08-12 10:37:48,120] {standard_task_runner.py:52} INFO - Started process 134290 to run task
[2021-08-12 10:37:48,124] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2021-08-11T00:00:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/subdag_example.py', '--cfg-path', '/tmp/tmpicc4ro2g', '--error-file', '/tmp/tmp0vsjpd23']
[2021-08-12 10:37:48,124] {standard_task_runner.py:77} INFO - Job 36: Subtask task_3
[2021-08-12 10:37:48,145] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [running]> on host adam
[2021-08-12 10:37:48,166] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-08-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-11T00:00:00+00:00
[2021-08-12 10:37:48,167] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 10:37:48,167] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'ls']
[2021-08-12 10:37:48,173] {subprocess.py:74} INFO - Output:
[2021-08-12 10:37:48,176] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 10:37:48,187] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20210811T000000, start_date=20210812T083748, end_date=20210812T083748
[2021-08-12 10:37:48,204] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 10:37:48,215] {local_task_job.py:149} INFO - Task exited with return code 0
[2021-08-12 10:38:43,964] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [queued]>
[2021-08-12 10:38:43,970] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [queued]>
[2021-08-12 10:38:43,970] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:38:43,970] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 10:38:43,970] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:38:43,978] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_3> on 2021-08-11T00:00:00+00:00
[2021-08-12 10:38:43,980] {standard_task_runner.py:52} INFO - Started process 135675 to run task
[2021-08-12 10:38:43,985] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2021-08-11T00:00:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/subdag_example.py', '--cfg-path', '/tmp/tmpina_jhf7', '--error-file', '/tmp/tmp08r90fdm']
[2021-08-12 10:38:43,986] {standard_task_runner.py:77} INFO - Job 36: Subtask task_3
[2021-08-12 10:38:44,010] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2021-08-11T00:00:00+00:00 [running]> on host adam
[2021-08-12 10:38:44,034] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-08-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-11T00:00:00+00:00
[2021-08-12 10:38:44,035] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 10:38:44,035] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'ls /Documents']
[2021-08-12 10:38:44,040] {subprocess.py:74} INFO - Output:
[2021-08-12 10:38:44,042] {subprocess.py:78} INFO - ls: cannot access '/Documents': No such file or directory
[2021-08-12 10:38:44,042] {subprocess.py:82} INFO - Command exited with return code 2
[2021-08-12 10:38:44,047] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-12 10:38:44,048] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=parallel_dag, task_id=task_3, execution_date=20210811T000000, start_date=20210812T083843, end_date=20210812T083844
[2021-08-12 10:38:44,075] {local_task_job.py:149} INFO - Task exited with return code 1
