[2021-08-12 17:18:52,835] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_2 2021-08-12T15:18:49.090811+00:00 [queued]>
[2021-08-12 17:18:52,841] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_2 2021-08-12T15:18:49.090811+00:00 [queued]>
[2021-08-12 17:18:52,841] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 17:18:52,841] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 17:18:52,841] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 17:18:52,847] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_2> on 2021-08-12T15:18:49.090811+00:00
[2021-08-12 17:18:52,849] {standard_task_runner.py:52} INFO - Started process 147115 to run task
[2021-08-12 17:18:52,853] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task_2', '2021-08-12T15:18:49.090811+00:00', '--job-id', '202', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpbjen8_ex', '--error-file', '/tmp/tmp_649v7x_']
[2021-08-12 17:18:52,854] {standard_task_runner.py:77} INFO - Job 202: Subtask task_2
[2021-08-12 17:18:52,873] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task_2 2021-08-12T15:18:49.090811+00:00 [running]> on host adam
[2021-08-12 17:18:52,897] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-08-12T15:18:49.090811+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-12T15:18:49.090811+00:00
[2021-08-12 17:18:52,897] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 17:18:52,897] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2021-08-12 17:18:52,903] {subprocess.py:74} INFO - Output:
[2021-08-12 17:18:52,904] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-12 17:18:52,909] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/adam/.virtualenvs/airflow_telia/lib/python3.9/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-12 17:18:52,910] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=trigger_rule, task_id=task_2, execution_date=20210812T151849, start_date=20210812T151852, end_date=20210812T151852
[2021-08-12 17:18:52,944] {local_task_job.py:149} INFO - Task exited with return code 1
